services:
  - type: web
    name: aoa-inventario-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: NODE_ENV
        value: production
